// <auto-generated />
using Lab10.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab10.Migrations
{
    [DbContext(typeof(StudentAdttendanceContext))]
    partial class StudentAdttendanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Lab10.Models.Student", b =>
                {
                    b.Property<int>("StuentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StuentId"));

                    b.Property<double>("Attendance_Percentage")
                        .HasColumnType("double");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("StuentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StuentId = 1,
                            Attendance_Percentage = 86.5,
                            Semester = 6
                        },
                        new
                        {
                            StuentId = 2,
                            Attendance_Percentage = 88.5,
                            Semester = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
